uploads = []
outputs = []

[[generated]]
id = "RWWV63mbC9Ga0zeBiO187"
uri = "file://Frontend/src/assets/logo-light-new.png"
type = "image"
title = "sciparser logo light mode"

[[generated]]
id = "S49HNxzOzbU3Gg40a0BXn"
uri = "file://Frontend/src/assets/logo-dark-new.png"
type = "image"
title = "sciparser logo dark mode"

[[generated]]
id = "haGJ7toC7q_dkKnN1jWWU"
uri = "file://Frontend/src/assets/logo-dark-blackbg.png"
type = "image"
title = "sciparser logo dark mode black bg"

[[generated]]
id = "_tw95DNifwxddtdZvOZI7"
uri = "file://Frontend/src/assets/logo-light-final.png"
type = "image"
title = "sciparser wordmark light"

[[generated]]
id = "vwAq2BLHgfq6BOtDRq9ZM"
uri = "file://Frontend/src/assets/logo-dark-final-blackbg.png"
type = "image"
title = "sciparser wordmark dark blackbg"
